DROP TABLE SQA_REOINT_FILE_UPLOAD_TRKING CASCADE CONSTRAINTS;

CREATE TABLE SQA_REOINT_FILE_UPLOAD_TRKING
(
  FILE_NAME     VARCHAR2(255 BYTE),
  UPLOAD_USER   VARCHAR2(255 BYTE),
  UPLOAD_DT     DATE                            DEFAULT SYSDATE,
  INSERT_COUNT  NUMBER,
  UPDATE_COUNT  NUMBER,
  ERROR_COUNT   NUMBER,
  REVIEW_COUNT  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON SQA_REOINT_FILE_UPLOAD_TRKING TO RDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_REOINT_FILE_UPLOAD_TRKING TO RDM_RW;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SQA_REOINT_FILE_UPLOAD_TRKING TO TEST_RW_ROLE;
