DROP TABLE SQA_TD_QUEUE_PROCESSOR_ALT CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_QUEUE_PROCESSOR_ALT
(
  PROCESSORS_PID  NUMBER                        NOT NULL,
  PID             NUMBER,
  PICK_ORDER      NUMBER                        NOT NULL,
  LOGIN           VARCHAR2(25 BYTE)             NOT NULL,
  STATUS          VARCHAR2(10 BYTE)             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SQA_ALT_PROCESSOR_IDX ON SQA_TD_QUEUE_PROCESSOR_ALT
(PROCESSORS_PID, PID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SQA_ALT_PROCESSOR_POS ON SQA_TD_QUEUE_PROCESSOR_ALT
(PROCESSORS_PID, PICK_ORDER)
LOGGING
NOPARALLEL;
