ALTER TABLE SQA_ICC_LOAN
 DROP PRIMARY KEY CASCADE;

DROP TABLE SQA_ICC_LOAN CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_LOAN
(
  P_ID                  NUMBER(10),
  IS_CURRENT            NUMBER(10),
  LOAN_NUMBER           VARCHAR2(100 BYTE),
  CLIENT_CODE           VARCHAR2(100 BYTE),
  REVIEWED_BY           VARCHAR2(100 BYTE),
  QC_OUTCOME            VARCHAR2(100 BYTE),
  COMMENTS              VARCHAR2(255 BYTE),
  ICC_DECISION          VARCHAR2(100 BYTE),
  CONVEY_AS_IS          VARCHAR2(100 BYTE),
  DATE_UPLOADED         DATE,
  DATE_REVIEWED         DATE,
  COUNT_IMPEDIMENTS     NUMBER(10),
  DATA_SOURCE           VARCHAR2(100 BYTE),
  UPDATER               VARCHAR2(100 BYTE),
  BILLER                VARCHAR2(100 BYTE),
  CASE_NUMBER           VARCHAR2(100 BYTE),
  STATE                 VARCHAR2(50 BYTE),
  CLIENT_LOAN_STATUS    VARCHAR2(100 BYTE),
  DATE_FTV              DATE,
  DATE_CONVEY_DEADLINE  DATE,
  DATE_SALE             DATE,
  DATE_INITIAL_ICC      DATE,
  DATE_ICC              DATE,
  RESPONSIBLE_UPDATER   VARCHAR2(100 BYTE),
  SERVICE_LINE          VARCHAR2(100 BYTE),
  DATE_RECONVEY         DATE,
  REVIEW_ORIGIN         VARCHAR2(100 BYTE),
  WORK_ORDER            NUMBER(20)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SQA_ICC_LOAN_PK ON SQA_ICC_LOAN
(P_ID)
LOGGING
NOPARALLEL;


ALTER TABLE SQA_ICC_LOAN ADD (
  CONSTRAINT SQA_ICC_LOAN_PK
  PRIMARY KEY
  (P_ID)
  USING INDEX SQA_ICC_LOAN_PK
  ENABLE VALIDATE);

GRANT DELETE, SELECT, UPDATE ON SQA_ICC_LOAN TO IPP$LIBRARIAN;
