ALTER TABLE SQA_ICC_FILE_TYPES
 DROP PRIMARY KEY CASCADE;

DROP TABLE SQA_ICC_FILE_TYPES CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_FILE_TYPES
(
  PID               NUMBER,
  FILE_TYPE         VARCHAR2(200 BYTE),
  COMMENTS          VARCHAR2(1000 BYTE),
  LOAD_PAGE_NO      NUMBER,
  REPORT_PAGE_ITEM  VARCHAR2(100 BYTE),
  REPORT_PAGE_NO    NUMBER,
  LOAD_PAGE_ITEM    VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0053543.
--  The object is created when the parent object is created.

ALTER TABLE SQA_ICC_FILE_TYPES ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, SELECT, UPDATE ON SQA_ICC_FILE_TYPES TO IPP$LIBRARIAN;

GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_ICC_FILE_TYPES TO RDM_RW;
