DROP TABLE SQA_TD_DATA_KEYS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_DATA_KEYS
(
  SPIPROPERTYID   VARCHAR2(30 BYTE),
  LOANNUMBER      VARCHAR2(50 BYTE),
  LOANTYPE        VARCHAR2(6 BYTE)              NOT NULL,
  CLIENT          VARCHAR2(6 BYTE),
  ORDERNUMBER     VARCHAR2(50 BYTE),
  WORKCODE        VARCHAR2(15 BYTE)             NOT NULL,
  CONTRACTORCODE  VARCHAR2(50 BYTE)             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
