DROP TABLE SQA_REOINT_FILE_IMPORT_STAGE CASCADE CONSTRAINTS;

CREATE TABLE SQA_REOINT_FILE_IMPORT_STAGE
(
  LOAN_NUM   VARCHAR2(255 BYTE),
  ORDER_NUM  VARCHAR2(255 BYTE),
  WORK_CODE  VARCHAR2(255 BYTE),
  STATUS     VARCHAR2(255 BYTE),
  UPLOAD_DT  DATE                               DEFAULT SYSDATE,
  ADDR_1     VARCHAR2(255 BYTE),
  ADDR_2     VARCHAR2(255 BYTE),
  CITY       VARCHAR2(255 BYTE),
  ST         VARCHAR2(255 BYTE),
  ZIP        VARCHAR2(255 BYTE),
  CLIENT     VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON SQA_REOINT_FILE_IMPORT_STAGE TO RDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_REOINT_FILE_IMPORT_STAGE TO RDM_RW;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SQA_REOINT_FILE_IMPORT_STAGE TO TEST_RW_ROLE;
