ALTER TABLE SQA_ICC_FILES_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE SQA_ICC_FILES_LIST CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_FILES_LIST
(
  PID            NUMBER,
  FILE_TYPE      NUMBER,
  FILE_NAME      VARCHAR2(1000 BYTE),
  RECORDCNT      NUMBER,
  LOAD_DATE      DATE,
  LOADED_BY      VARCHAR2(100 BYTE),
  COMMENTS       VARCHAR2(1000 BYTE),
  BEGIN_LOAD_ID  NUMBER,
  END_LOAD_ID    NUMBER,
  LOADED         NUMBER                         DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0053123.
--  The object is created when the parent object is created.

ALTER TABLE SQA_ICC_FILES_LIST ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_ICC_FILES_LIST TO IPP$LIBRARIAN;

GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_ICC_FILES_LIST TO RDM_RW;
