DROP TABLE SQA_TD_YN CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_YN
(
  PID        NUMBER,
  DETAIL_ID  NUMBER,
  SQA_TD_YN  VARCHAR2(5 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_TD_YN TO RDM_RW;
