DROP TABLE SQA_TD_DATA_ETL CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_DATA_ETL
(
  SPIPROPERTYID   VARCHAR2(30 BYTE),
  LOANNUMBER      VARCHAR2(50 BYTE),
  LOANTYPE        VARCHAR2(6 BYTE),
  CLIENT          VARCHAR2(6 BYTE),
  ADDRESSLINE1    VARCHAR2(255 BYTE),
  ADDRESSLINE2    VARCHAR2(255 BYTE),
  CITY            VARCHAR2(255 BYTE),
  STATE           VARCHAR2(2 BYTE),
  ZIP             VARCHAR2(9 BYTE),
  ORDERNUMBER     VARCHAR2(50 BYTE),
  ORDERDATE       DATE,
  WORKCODE        VARCHAR2(15 BYTE),
  COMPLETEDDATE   DATE,
  CONTRACTORCODE  VARCHAR2(50 BYTE),
  MORTGAGORNAME   VARCHAR2(120 BYTE),
  SALEDATE        DATE,
  SECUREDDATE     DATE,
  WINTERIZEDDATE  DATE,
  INITIALICCDATE  DATE,
  LASTICCDATE     DATE,
  CONVEYDATE      DATE,
  INVESTORNUMBER  VARCHAR2(255 BYTE),
  BILLINGCODE     VARCHAR2(4 BYTE),
  REPORT_SEGMENT  VARCHAR2(20 BYTE),
  WORK_GROUP      VARCHAR2(20 BYTE),
  NBR_QUESTIONS   NUMBER,
  PID             NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
