ALTER TABLE SQA_VENDOR_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE SQA_VENDOR_LIST CASCADE CONSTRAINTS;

CREATE TABLE SQA_VENDOR_LIST
(
  VENDOR_ID              NUMBER,
  VENDOR_CODE            VARCHAR2(40 BYTE),
  FOLLOW_UP              VARCHAR2(40 BYTE),
  FOLLOW_UP_SAT          VARCHAR2(40 BYTE),
  FOLLOW_UP_DTE          DATE,
  STANDING               NUMBER,
  NBR_WORKORDERS         NUMBER,
  ACTIVE                 NUMBER,
  LAST_REVIEW            DATE,
  REVIEWED_BY            VARCHAR2(100 BYTE),
  SEGMENTS               VARCHAR2(20 BYTE),
  CAP_HOLD               NUMBER,
  BATCH_NO               NUMBER,
  WORKCODE               VARCHAR2(20 BYTE),
  ASSIGNED_TO            INTEGER,
  COMPLETED_BY           INTEGER,
  START_COUNTER_DATE     DATE,
  FOLLOW_UP_CAT          VARCHAR2(100 BYTE),
  THIRTY_FIFTY_DAY_RULE  NUMBER,
  ASSIGN_IT              NUMBER,
  FOLLOW_UP_RES          VARCHAR2(20 BYTE),
  NBR_COMPLETED          NUMBER,
  NEXT_REVIEW            DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SQA_VENDOR_LIST.SEGMENTS IS 'REO, FNMA, P&P';



CREATE UNIQUE INDEX SQA_VENDOR_LIST_PK01 ON SQA_VENDOR_LIST
(VENDOR_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SQL_VENDOR_UK01 ON SQA_VENDOR_LIST
(VENDOR_CODE, SEGMENTS)
LOGGING
NOPARALLEL;


ALTER TABLE SQA_VENDOR_LIST ADD (
  CONSTRAINT SQA_VENDOR_LIST_PK01
  PRIMARY KEY
  (VENDOR_ID)
  USING INDEX SQA_VENDOR_LIST_PK01
  ENABLE VALIDATE);
