ALTER TABLE SQA_SYS_VARIABLES
 DROP PRIMARY KEY CASCADE;

DROP TABLE SQA_SYS_VARIABLES CASCADE CONSTRAINTS;

CREATE TABLE SQA_SYS_VARIABLES
(
  VARIABLE_NAME   VARCHAR2(100 BYTE),
  VARIABLE_VALUE  VARCHAR2(4000 BYTE),
  COMMENTS        VARCHAR2(300 BYTE),
  PID             NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


--  There is no statement for index RDM.SYS_C0053250.
--  The object is created when the parent object is created.

ALTER TABLE SQA_SYS_VARIABLES ADD (
  PRIMARY KEY
  (PID)
  ENABLE VALIDATE);
