DROP TABLE SQA_TD_COL_TO_HEADING CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_COL_TO_HEADING
(
  PID          NUMBER,
  COLUMN_NAME  VARCHAR2(100 BYTE),
  HEADING      VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
