DROP TABLE SQA_QC_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE SQA_QC_DETAILS
(
  PID                  NUMBER,
  MASTER_ID            NUMBER,
  QC_COORDINATOR       VARCHAR2(100 BYTE),
  EMPLOYEE_TYPE        VARCHAR2(100 BYTE),
  LOAN_NUMBER          VARCHAR2(40 BYTE),
  ORDER_NUMBER         VARCHAR2(40 BYTE),
  WORK_CODE            VARCHAR2(40 BYTE),
  PROCESSOR            VARCHAR2(100 BYTE),
  EMPL_SUPERVISOR      VARCHAR2(100 BYTE),
  EMPL_TEAM_LEAD       VARCHAR2(100 BYTE),
  JOB_TITLE            VARCHAR2(200 BYTE),
  INSPECTION_REVIEW    VARCHAR2(100 BYTE),
  WO_ENTRY_COMPON      VARCHAR2(100 BYTE),
  WO_INSTR_COMPL_AUD   VARCHAR2(100 BYTE),
  WO_INSTR_COMPL       VARCHAR2(100 BYTE),
  BID_SUB_APPEAL       VARCHAR2(100 BYTE),
  SPI_GLASS_DAMAGE     VARCHAR2(100 BYTE),
  SPI_GLASS_BID        VARCHAR2(100 BYTE),
  HARDCODING_STATUS    VARCHAR2(100 BYTE),
  INVOICING_ACCURATE   VARCHAR2(100 BYTE),
  ARCHER_CARCH_SPI     VARCHAR2(100 BYTE),
  COMMENTS             VARCHAR2(4000 BYTE),
  TOTAL_POINTS_EARNED  NUMBER,
  POSSIBLE_POINTS      NUMBER,
  PERCENT_SCORE        NUMBER,
  MGMT_REVIEW_DATE     DATE,
  PASS_FAIL            VARCHAR2(100 BYTE),
  MGMT_COMMENTS        VARCHAR2(4000 BYTE),
  REBUTTAL_DEADLINE    DATE,
  REBUTTAL_DATE        DATE,
  REBUTTAL_OUTCOME     VARCHAR2(200 BYTE),
  NON_REBUTTAL         VARCHAR2(1000 BYTE),
  WORKING              NUMBER,
  COMPLETED            DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
