DROP TABLE SQA_HIRISK_INIT_HEADERS CASCADE CONSTRAINTS;

CREATE TABLE SQA_HIRISK_INIT_HEADERS
(
  COLNAME    VARCHAR2(40 BYTE),
  COLHEADER  VARCHAR2(300 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON SQA_HIRISK_INIT_HEADERS TO RDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_HIRISK_INIT_HEADERS TO RDM_RW;
