DROP TABLE SQA_QC_MASTER_STG CASCADE CONSTRAINTS;

CREATE TABLE SQA_QC_MASTER_STG
(
  CLIENT        VARCHAR2(40 BYTE),
  LOAN_TYPE     VARCHAR2(40 BYTE),
  WORK_CODE     VARCHAR2(40 BYTE),
  VENDOR_CODE   VARCHAR2(40 BYTE),
  LOAN_NUMBER   VARCHAR2(40 BYTE),
  ORDER_NUMBER  VARCHAR2(40 BYTE),
  QC_SEGMENT    VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
