DROP TABLE SQA_REOINT_EXT_ORDER_REASON CASCADE CONSTRAINTS;

CREATE TABLE SQA_REOINT_EXT_ORDER_REASON
(
  PID                    NUMBER,
  DETAIL_ID              NUMBER,
  EXTERIOR_ORDER_REASON  VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
