DROP TABLE SQA_ICC_WORK_ASSIGNED_HIST CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_WORK_ASSIGNED_HIST
(
  LOAN_NUMBER                  VARCHAR2(40 BYTE),
  CLIENT_NAME                  VARCHAR2(40 BYTE),
  REVIEWER                     VARCHAR2(40 BYTE),
  DATA_SOURCE                  VARCHAR2(20 BYTE),
  RECONVEY_STATUS              VARCHAR2(100 BYTE),
  CAR_NAME                     VARCHAR2(40 BYTE),
  STATE                        VARCHAR2(10 BYTE),
  CLIENT_SPECIFIC_LOAN_STATUS  VARCHAR2(100 BYTE),
  FTV                          VARCHAR2(20 BYTE),
  SALE_DATE                    VARCHAR2(40 BYTE),
  CURRENT_CONVEYANCE_DEADLINE  VARCHAR2(40 BYTE),
  INITIAL_ICC_DATE             VARCHAR2(40 BYTE),
  ICC_DATE                     VARCHAR2(40 BYTE),
  CASE_NUMBER                  VARCHAR2(40 BYTE),
  UPDATER                      VARCHAR2(40 BYTE),
  BILLER                       VARCHAR2(40 BYTE),
  LOAD_ID                      NUMBER,
  FILE_ID                      NUMBER,
  LOAD_DATE                    DATE,
  USER_ID                      NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_WORK_ASSIGNED_HIST TO IPP$LIBRARIAN;
