DROP TABLE SQA_REOINT_DATA_AUD CASCADE CONSTRAINTS;

CREATE TABLE SQA_REOINT_DATA_AUD
(
  AUDIT_DT                   DATE               DEFAULT SYSDATE,
  CLIENT                     VARCHAR2(10 BYTE),
  SQA_REP                    VARCHAR2(50 BYTE),
  INSPECTOR_CODE             VARCHAR2(25 BYTE),
  LOAN_NUM                   VARCHAR2(25 BYTE),
  INSPECTOR_ORDER_NUM        NUMBER,
  INTERIOR_VENDOR            VARCHAR2(25 BYTE),
  ORDER_OPENED               VARCHAR2(100 BYTE) DEFAULT NULL,
  SQA_WO_NUM                 NUMBER,
  SQA_FU_REASON_1            VARCHAR2(100 BYTE),
  SQA_FU_REASON_2            VARCHAR2(100 BYTE),
  SQA_FU_REASON_3            VARCHAR2(100 BYTE),
  ADDITONAL_ORDER_OPENED     VARCHAR2(255 BYTE),
  EXTERIOR_VENDOR            VARCHAR2(25 BYTE),
  GCFU_W0_NUM                NUMBER,
  GCFU_REASON_1              VARCHAR2(100 BYTE),
  GCFU_REASON_2              VARCHAR2(100 BYTE),
  GCFU_REASON_3              VARCHAR2(100 BYTE),
  WORKING                    VARCHAR2(5 BYTE)   DEFAULT NULL,
  UPDATER_ERROR              VARCHAR2(5 BYTE),
  GCFU_OPENED                VARCHAR2(5 BYTE),
  CRITICAL_ERROR             VARCHAR2(5 BYTE),
  GOOD_INT_PHOTOS            VARCHAR2(5 BYTE),
  GOOD_EXT_PHOTOS            VARCHAR2(5 BYTE),
  NEED_LANDSCAPING_PCKG      VARCHAR2(5 BYTE),
  NEED_GUTTER_ROOF_PCKG      VARCHAR2(5 BYTE),
  NEED_SECURE_VIEW_BOARDING  VARCHAR2(5 BYTE),
  ADDR_1                     VARCHAR2(255 BYTE),
  ADDR_2                     VARCHAR2(255 BYTE),
  CITY                       VARCHAR2(255 BYTE),
  ST                         VARCHAR2(5 BYTE),
  ZIP                        VARCHAR2(15 BYTE),
  SQAGC_OPENED               VARCHAR2(100 BYTE),
  FRONT_YARD_CUT             VARCHAR2(5 BYTE),
  BACK_YARD_CUT              VARCHAR2(5 BYTE),
  WEED_WHACKING              VARCHAR2(5 BYTE),
  EDGED_PAVED_AREAS          VARCHAR2(5 BYTE),
  SHRUBS_CUT                 VARCHAR2(5 BYTE),
  FREE_OF_WEEDS              VARCHAR2(5 BYTE),
  LEAVES_REMOVED             VARCHAR2(5 BYTE),
  WHITE_GLOVE_PHOTO          VARCHAR2(5 BYTE),
  LAST_UPDATE_DT             DATE,
  FILE_UPLOAD_DT             DATE,
  FILE_UPLOAD_ID             NUMBER,
  STATUS                     VARCHAR2(25 BYTE),
  WORK_CODE                  VARCHAR2(10 BYTE),
  SAVED                      VARCHAR2(5 BYTE),
  SQA_DATE                   DATE,
  COMPLETED                  VARCHAR2(5 BYTE),
  INSP_ORIGIN                VARCHAR2(50 BYTE),
  LANDSCAPE_PKG_USED         VARCHAR2(50 BYTE),
  ROOF_GUTTER_PKG_USED       VARCHAR2(50 BYTE),
  EXT_WINDOW_CLEAN_USED      VARCHAR2(50 BYTE),
  POWER_WASH_COMPLETED       VARCHAR2(50 BYTE),
  HANDRAIL_COMPLETED         VARCHAR2(50 BYTE),
  GUTTER_REPAIR_COMPLETED    VARCHAR2(50 BYTE),
  RECORD_RECEIVED_DT         DATE,
  PROCESSING_TIME            VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SQA_DATA_AUD_LNCLIENT_IDX ON SQA_REOINT_DATA_AUD
(AUDIT_DT, LOAN_NUM, CLIENT)
LOGGING
NOPARALLEL;


GRANT SELECT ON SQA_REOINT_DATA_AUD TO RDM_RO;

GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_REOINT_DATA_AUD TO RDM_RW;

GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SQA_REOINT_DATA_AUD TO TEST_RW_ROLE;
