DROP TABLE SQA_TD_EMPLS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_EMPLS
(
  LOGIN         VARCHAR2(40 BYTE),
  DATA_DATE     DATE                            DEFAULT SYSDATE,
  STATUS        NUMBER,
  PID           NUMBER,
  EMAILADDRESS  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
