DROP TABLE SQA_TD_STYLE_COLOR CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_STYLE_COLOR
(
  PID         NUMBER,
  COLOR_NAME  VARCHAR2(100 BYTE),
  COLOR_DEF   VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
