DROP TABLE SQA_ICC_CARDS_RPT_STG CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_CARDS_RPT_STG
(
  LOAN              VARCHAR2(40 BYTE),
  MORT_NAME         VARCHAR2(100 BYTE),
  ADDRESS_LINE1     VARCHAR2(200 BYTE),
  ADDRESS_LINE2     VARCHAR2(200 BYTE),
  CITY              VARCHAR2(60 BYTE),
  STATE             VARCHAR2(10 BYTE),
  ZIP               VARCHAR2(20 BYTE),
  SALE_DT           VARCHAR2(40 BYTE),
  SECURED_DT        VARCHAR2(40 BYTE),
  WINTERIZED_DT     VARCHAR2(40 BYTE),
  INITIAL_ICC_DT    VARCHAR2(40 BYTE),
  REPORTED_ICC_DT   VARCHAR2(40 BYTE),
  COMPLETED_ICC_DT  VARCHAR2(40 BYTE),
  CONVEY_DATE       VARCHAR2(40 BYTE),
  INVESTOR          VARCHAR2(40 BYTE),
  CLIENT            VARCHAR2(40 BYTE),
  LOAD_ID           NUMBER,
  FILE_ID           NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_CARDS_RPT_STG TO IPP$LIBRARIAN;
