DROP TABLE SQA_TD_REPORT_SUMMARY CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_REPORT_SUMMARY
(
  BATCH_NO        NUMBER,
  COLUMN_NAME     VARCHAR2(100 BYTE),
  QUESTION        VARCHAR2(1000 BYTE),
  TOTAL_PER_TASK  NUMBER,
  TASK_COMPLIENT  VARCHAR2(10 BYTE),
  REPORT_ORDER    NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
