DROP TABLE SQA_TD_BRANCH_PAGES CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_BRANCH_PAGES
(
  PID            NUMBER,
  CLIENT         VARCHAR2(10 BYTE),
  LOAN_TYPE      VARCHAR2(10 BYTE),
  WORK_CODE      VARCHAR2(10 BYTE),
  PAGE_NBR       NUMBER,
  COMMENTS       VARCHAR2(255 BYTE),
  NBR_QUESTIONS  NUMBER,
  FORM_PAGE      NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
