DROP TABLE SQA_LOV CASCADE CONSTRAINTS;

CREATE TABLE SQA_LOV
(
  PID               NUMBER,
  LOV_TABLE         VARCHAR2(255 BYTE),
  LOV_NAME          VARCHAR2(255 BYTE),
  APPLICATION_NAME  VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_LOV TO RDM_RW;
