DROP TABLE SQA_ICC_ASSIGNMENT_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_ASSIGNMENT_TEMPLATE
(
  LOANNUMBER        VARCHAR2(50 BYTE),
  CLIENTCODE        VARCHAR2(50 BYTE),
  ORDERNUMBER       VARCHAR2(50 BYTE),
  RECONVEYDATE      DATE,
  CONVEYSTATUS      VARCHAR2(100 BYTE),
  SALEDATE          DATE,
  WORKCODEDESC      VARCHAR2(200 BYTE),
  ORDERDATE         DATE,
  RECONVEY          VARCHAR2(30 BYTE),
  DATA_SOURCE       VARCHAR2(200 BYTE),
  BACKLOG           VARCHAR2(30 BYTE),
  REPORT_DATE       DATE,
  LATEST_PASS_DATE  DATE,
  LATEST_FAIL_DATE  DATE,
  ASSIGNMENT        VARCHAR2(100 BYTE),
  PID               NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_ASSIGNMENT_TEMPLATE TO IPP$LIBRARIAN;
