DROP TABLE SQA_REOINT_ORDER_OPENED CASCADE CONSTRAINTS;

CREATE TABLE SQA_REOINT_ORDER_OPENED
(
  PID           NUMBER,
  DETAIL_ID     NUMBER,
  ORDER_OPENED  VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON SQA_REOINT_ORDER_OPENED TO RDM_RO_ROLE;
