DROP TABLE SQA_ICC_MV CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_MV
(
  LOAN_NUMBER                  VARCHAR2(50 BYTE),
  WORK_ORDER_NUMBER            VARCHAR2(50 BYTE) NOT NULL,
  WORK_CODE_SHORT_NAME         VARCHAR2(15 BYTE) NOT NULL,
  CLIENT_CODE                  VARCHAR2(10 BYTE),
  COMPLETION_DATE_ENTERED      DATE,
  COMPLETED_DATE               DATE,
  SALE_DATE                    DATE,
  IS_POOL_SECURE               VARCHAR2(10 BYTE),
  IS_HOT_TUB_SECURE            VARCHAR2(10 BYTE),
  SUMP_PUMP                    VARCHAR2(10 BYTE),
  IS_SUMP_PUMP_OPERATIONAL     VARCHAR2(10 BYTE),
  DEHUMIDIFIER                 VARCHAR2(10 BYTE),
  IS_DEHUMIDIFIER_OPERATIONAL  VARCHAR2(10 BYTE),
  GARAGE_SECURE                VARCHAR2(20 BYTE),
  OUT_BUILDING_SECURE          VARCHAR2(20 BYTE),
  CRAWLSPACE_SECURE            VARCHAR2(20 BYTE),
  GRASS_HEIGHT                 NUMBER(6,2),
  PROPERTY_SECURE              VARCHAR2(30 BYTE),
  NEW_DAMAGE                   VARCHAR2(30 BYTE),
  SEVERE_DAMAGE                VARCHAR2(30 BYTE),
  IS_ROOF_TARPED               VARCHAR2(20 BYTE),
  ACTIVE_ROOF_LEAK             VARCHAR2(20 BYTE),
  A_C_UNIT_PRESENT             VARCHAR2(500 BYTE),
  ANTIFREEZE_IN_ALL            VARCHAR2(20 BYTE),
  DID_GAIN_ACCESS              VARCHAR2(50 BYTE),
  OCCUPANCY_STATUS             VARCHAR2(30 BYTE),
  LOAN_TYPE_CODE               VARCHAR2(6 BYTE) NOT NULL,
  VISIBLE_FLOOD_DAMAGE         VARCHAR2(1 BYTE),
  VISIBLE_MOLD_PRESENT         VARCHAR2(1 BYTE),
  VISIBLE_ROOF_LEAK            VARCHAR2(1 BYTE),
  VISIBLE_VANDALISM            VARCHAR2(1 BYTE),
  PERSONAL_PROPERTY            VARCHAR2(250 BYTE),
  DEBRIS                       VARCHAR2(250 BYTE),
  RECONVEY_DATE                DATE,
  RECONVEY_TYPE                VARCHAR2(40 BYTE),
  LOAN_TYPE                    VARCHAR2(10 BYTE),
  ORDER_NBR                    VARCHAR2(40 BYTE),
  ORDER_STATUS                 VARCHAR2(20 BYTE),
  ORDER_DATE                   DATE,
  WORK_CODE                    VARCHAR2(100 BYTE),
  CONVEY_STATUS                VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SQA_ICC_CC_IX ON SQA_ICC_MV
(CLIENT_CODE)
LOGGING
NOPARALLEL;


CREATE INDEX SQA_ICC_LN_IX ON SQA_ICC_MV
(LOAN_NUMBER)
LOGGING
NOPARALLEL;


CREATE INDEX SQA_ICC_WON_IX ON SQA_ICC_MV
(WORK_ORDER_NUMBER)
LOGGING
NOPARALLEL;


DROP SYNONYM SQA_ICC;

CREATE OR REPLACE SYNONYM SQA_ICC FOR SQA_ICC_MV;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_MV TO IPP$LIBRARIAN;
