DROP TABLE SQA_ICC_IMPEDIMENTS_STG CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_IMPEDIMENTS_STG
(
  LOAN_NUMBER    VARCHAR2(50 BYTE),
  CLIENT_CODE    VARCHAR2(20 BYTE),
  REVIEWED_BY    VARCHAR2(100 BYTE),
  IMPEDIMENT     VARCHAR2(1000 BYTE),
  WORK_ORDER     VARCHAR2(50 BYTE),
  COMMENTS       VARCHAR2(4000 BYTE),
  DATE_REVIEWED  DATE,
  PID            NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_IMPEDIMENTS_STG TO IPP$LIBRARIAN;
