DROP TABLE SQA_ICC_ASSIGNED_CAT CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_ASSIGNED_CAT
(
  PID            NUMBER,
  CATEGORIES     VARCHAR2(200 BYTE),
  CATEGORY_DESC  VARCHAR2(4000 BYTE),
  ACTIVE         VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_ASSIGNED_CAT TO IPP$LIBRARIAN;
