ALTER TABLE SQA_TD_DATA_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP TABLE SQA_TD_DATA_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_DATA_DETAILS
(
  DETAIL_ID       NUMBER,
  MASTER_ID       NUMBER,
  BATCH_NO        NUMBER,
  CONTRACTOR_ID   NUMBER,
  CLIENT          VARCHAR2(100 BYTE),
  CONTRACTOR      VARCHAR2(100 BYTE),
  REPORT_SEGMENT  VARCHAR2(20 BYTE),
  REVIEW_ID       NUMBER,
  RUNNING_SCORE   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SQA_TD_DATA_DETAILS ON SQA_TD_DATA_DETAILS
(DETAIL_ID)
LOGGING
NOPARALLEL;


CREATE INDEX SQA_TD_DATA_DETAILS_BATCH_NO ON SQA_TD_DATA_DETAILS
(MASTER_ID, BATCH_NO)
LOGGING
NOPARALLEL;


ALTER TABLE SQA_TD_DATA_DETAILS ADD (
  CONSTRAINT SQA_TD_DATA_DETAILS
  PRIMARY KEY
  (DETAIL_ID)
  USING INDEX SQA_TD_DATA_DETAILS
  ENABLE VALIDATE);
