DROP TABLE SQA_ICC_Y_PASS CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_Y_PASS
(
  PID    NUMBER,
  YN     NUMBER,
  PASS   VARCHAR2(10 BYTE),
  YESNO  VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_Y_PASS TO IPP$LIBRARIAN;
