DROP TABLE SQA_ICC_SECURITY_LEVELS CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_SECURITY_LEVELS
(
  LOGIN               VARCHAR2(40 BYTE),
  USER_ID             NUMBER,
  ICC_SECURITY_LEVEL  NUMBER,
  PID                 NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_SECURITY_LEVELS TO IPP$LIBRARIAN;
