DROP TABLE SQA_ICC_OVERALL CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_OVERALL
(
  LOANNUMBER     VARCHAR2(40 BYTE),
  CLIENT         VARCHAR2(20 BYTE),
  REVIEWER       VARCHAR2(100 BYTE),
  CAR_PROCESSOR  VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_OVERALL TO IPP$LIBRARIAN;
