DROP TABLE SQA_TD_CLASSES CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_CLASSES
(
  PID         NUMBER,
  CLASS_NAME  VARCHAR2(100 BYTE),
  CLASS_DEF   VARCHAR2(1000 BYTE),
  SHEET_NAME  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
