DROP TABLE SQA_TD_QUEUE_PROCESSORS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_QUEUE_PROCESSORS
(
  LOGIN   VARCHAR2(25 BYTE),
  STATUS  VARCHAR2(10 BYTE),
  PID     NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SQA_TD_QUEUE_PROCESSORS_UK01 ON SQA_TD_QUEUE_PROCESSORS
(LOGIN, PID)
LOGGING
NOPARALLEL;
