DROP TABLE SQA_EMAIL_ADDRESSES CASCADE CONSTRAINTS;

CREATE TABLE SQA_EMAIL_ADDRESSES
(
  PID            NUMBER,
  APP            VARCHAR2(100 BYTE),
  CONTACT_GROUP  VARCHAR2(100 BYTE),
  FIRST_NAME     VARCHAR2(100 BYTE),
  LAST_NAME      VARCHAR2(100 BYTE),
  EMAILADDRESS   VARCHAR2(200 BYTE),
  WORKSPACE      VARCHAR2(100 BYTE),
  EMAIL_OPTIONS  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SQA_EMAIL_ADDRESSES_PK01 ON SQA_EMAIL_ADDRESSES
(PID)
LOGGING
NOPARALLEL;
