DROP TABLE SQA_REOINT_SECURITY CASCADE CONSTRAINTS;

CREATE TABLE SQA_REOINT_SECURITY
(
  LOGIN                  VARCHAR2(25 BYTE),
  DATA_DATE              DATE                   DEFAULT SYSDATE,
  REOINT_SECURITY_LEVEL  NUMBER,
  PID                    NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
