DROP TABLE SQA_TD_EMAIL_LETTERS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_EMAIL_LETTERS
(
  LETTER_ID       NUMBER,
  LETTER_TYPE     VARCHAR2(300 BYTE),
  REPORT_SEGMENT  VARCHAR2(300 BYTE),
  CLIENT          VARCHAR2(300 BYTE),
  ENTRY_DATE      DATE,
  LETTER_BODY     VARCHAR2(4000 BYTE),
  COMMENTS        VARCHAR2(1000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
