DROP TABLE SQA_TD_XMLNS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_XMLNS
(
  PID       NUMBER,
  REF_NAME  VARCHAR2(100 BYTE),
  XMLNS     VARCHAR2(1000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON SQA_TD_XMLNS TO IPP$LIBRARIAN;
