DROP TABLE SQA_TD_WORK_GROUPS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_WORK_GROUPS
(
  PID         NUMBER,
  GROUP_NAME  VARCHAR2(20 BYTE),
  WORKCODE    VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
