DROP TABLE SQA_ICC_QAPP_UPLOAD_STG CASCADE CONSTRAINTS;

CREATE TABLE SQA_ICC_QAPP_UPLOAD_STG
(
  LOAN_NUMBER  VARCHAR2(40 BYTE),
  CLIENT_NAME  VARCHAR2(40 BYTE),
  REVIEWER     VARCHAR2(60 BYTE),
  CAR_NAME     VARCHAR2(40 BYTE),
  LOAD_ID      NUMBER,
  FILE_ID      NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT DELETE, SELECT, UPDATE ON SQA_ICC_QAPP_UPLOAD_STG TO IPP$LIBRARIAN;
