DROP TABLE SQA_TD_QUESTION_HEADINGS CASCADE CONSTRAINTS;

CREATE TABLE SQA_TD_QUESTION_HEADINGS
(
  PID          NUMBER,
  PAGE_NO      NUMBER,
  COLUMN_NAME  VARCHAR2(100 BYTE),
  HEADING      VARCHAR2(200 BYTE),
  COLUMN_NBR   NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SQA_TD_QUESTIION_HEADINGS_KEYS ON SQA_TD_QUESTION_HEADINGS
(PAGE_NO, COLUMN_NAME)
LOGGING
NOPARALLEL;
